### ISSUE TITLE
import failed after update:AttributeError: module 'enum' has no attribute 'StrEnum'

### ISSUE THREAD

**Issue by czcz1024** [Extraltodeus/sigmas_tools_and_the_golden_scheduler#7]
Traceback (most recent call last):
  File "D:\ai\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler\__init__.py", line 1, in <module>
    from .sigmas_merge import NODE_CLASS_MAPPINGS
  File "D:\ai\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler\sigmas_merge.py", line 29, in <module>
    class GraphScale(enum.StrEnum):
AttributeError: module 'enum' has no attribute 'StrEnum'

**Comment by vitosans** [comment]
Getting the same, I think it is a python 3.10 vs 3.11 issue. 

If you don't want to upgrade python.

sigmas_merge.py

`
from enum import Enum

class GraphScale(str, Enum):  # Replace StrEnum with str and Enum
    linear = "linear"
    log = "log"
`

**Comment by clayne** [comment]
Also seeing this:
```
Traceback (most recent call last):
  File "S:\stablediffusion\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\stablediffusion\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler\__init__.py", line 1, in <module>
    from .sigmas_merge import NODE_CLASS_MAPPINGS
  File "S:\stablediffusion\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler\sigmas_merge.py", line 29, in <module>
    class GraphScale(enum.StrEnum):
AttributeError: module 'enum' has no attribute 'StrEnum'

Cannot import S:\stablediffusion\ComfyUI\custom_nodes\sigmas_tools_and_the_golden_scheduler module for custom nodes: module 'enum' has no attribute 'StrEnum'
```

**Comment by Talae06** [comment]
Same here. Downgraded to committ 700839c21809e310dd7122e3544e4acae8d121d3 for now.

**Comment by clayne** [comment]
Seems like this is an issue because `enum.StrEnum` is python 3.11+ only: https://docs.python.org/3/library/enum.html#enum.StrEnum

**Comment by vitosans** [comment]
check my fork if you are on 3.10

**Comment by NeoAnthropocene** [comment]
> check my fork if you are on 3.10

@vitosans, [Your repo](https://github.com/Extraltodeus/sigmas_tools_and_the_golden_scheduler/blob/0cd216cd8dd5d7b95a8f8035e3e1b19f8d94307c/sigmas_merge.py) solved the problem with python 3.10.9 version. Thanks.
